# Generated by Django 5.0.4 on 2024-04-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=30)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('where_to_go', models.CharField(max_length=20)),
                ('number_of_tickets', models.IntegerField()),
            ],
        ),
    ]
